# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Nick Kasprzak  
email: nick.kasprzak@utexas.edu 
facebook_username: nick.kasprzak
twitter_username: nksprzak
github_username: nksprzak
address: 2505 Longivew St.
  - line: Austin, TX 78705
  - line:
  # Feel free to add more lines here 
telephone: 832-628-4047
copyright:

# API settings
google_api_key: AIzaSyDShLMyWKW7Etj9vlcsodoIha-QgN2416U 

# Build settings
markdown: kramdown
